spring.application.name: springboot-client
server.port: 8999
  
spring.datasource.url: jdbc:mysql://dev.ityx.de/test
spring.datasource.username: test
spring.datasource.password: test
spring.datasource.driver-class-name: com.mysql.jdbc.Driver

spring.jpa.hibernate.ddl-auto: update